# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('registetime', models.DateTimeField(auto_now_add=True)),
                ('issudit', models.BooleanField(default=True)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
